<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PRI1S77" failures="4" tests="4" name="Test" time="5.426" errors="0" timestamp="2021-02-14T21:17:24 IST">
  <testcase classname="DataDrivenTesting.createNewUser" name="createuser" time="4.485">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;201&amp;gt; but was:&amp;lt;204&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<204>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at DataDrivenTesting.validationSuite.validateStatusCode(validationSuite.java:18)
at DataDrivenTesting.createNewUser.createuser(createNewUser.java:42)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- createuser -->
  <testcase classname="DataDrivenTesting.createNewUser" name="createuser" time="4.488">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;201&amp;gt; but was:&amp;lt;204&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<204>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at DataDrivenTesting.validationSuite.validateStatusCode(validationSuite.java:18)
at DataDrivenTesting.createNewUser.createuser(createNewUser.java:42)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- createuser -->
  <testcase classname="DataDrivenTesting.createNewUser" name="createuser" time="4.483">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;201&amp;gt; but was:&amp;lt;204&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<204>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at DataDrivenTesting.validationSuite.validateStatusCode(validationSuite.java:18)
at DataDrivenTesting.createNewUser.createuser(createNewUser.java:42)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- createuser -->
  <testcase classname="DataDrivenTesting.createNewUser" name="createuser" time="4.484">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;201&amp;gt; but was:&amp;lt;204&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<201> but was:<204>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at DataDrivenTesting.validationSuite.validateStatusCode(validationSuite.java:18)
at DataDrivenTesting.createNewUser.createuser(createNewUser.java:42)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- createuser -->
</testsuite> <!-- Test -->
